"use client";

import { useEffect, useMemo, useState } from "react";
import { Card, Button, Input, Badge } from "@/shared/components";
import { useCopyToClipboard } from "@/shared/hooks/useCopyToClipboard";

const DEFAULT_BASE = "https://api.stali.vn/v1";
const DEFAULT_MODELS = [
  "claude-fable-5",
  "claude-sonnet-5",
  "claude-opus-5",
  "gpt-5.6-sol",
];

function normalizeBase(baseUrl) {
  const trimmed = String(baseUrl || "").trim().replace(/\/+$/, "");
  if (!trimmed) return "";
  return /\/v1$/i.test(trimmed) ? trimmed : `${trimmed}/v1`;
}

function parseModels(input) {
  const raw = String(input || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  return [...new Set(raw)];
}

export default function StaliSetupClient() {
  const [baseUrl, setBaseUrl] = useState(DEFAULT_BASE);
  const [apiKey, setApiKey] = useState("");
  const [modelsInput, setModelsInput] = useState(DEFAULT_MODELS.join(", "));
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const { copied, copy } = useCopyToClipboard(1800);
  const [preset, setPreset] = useState("openai");
  const [profileLoading, setProfileLoading] = useState(true);

  const selectedModels = useMemo(() => parseModels(modelsInput), [modelsInput]);
  const sampleModel = (result?.models || selectedModels)[0] || DEFAULT_MODELS[0];
  const localEndpoint = "http://localhost:20128/v1";

  const snippets = useMemo(() => {
    const key = result?.routerKey || "<router-api-key>";
    const model = sampleModel || "claude-sonnet-5";
    return {
      curl: `curl ${localEndpoint}/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer ${key}" \\
  -d '{
    "model": "${model}",
    "messages": [{"role":"user","content":"hello"}]
  }'`,
      openaiEnv: `OPENAI_BASE_URL=${localEndpoint}
OPENAI_API_KEY=${key}
OPENAI_MODEL=${model}`,
      claudeEnv: `ANTHROPIC_BASE_URL=${localEndpoint}
ANTHROPIC_API_KEY=${key}
ANTHROPIC_MODEL=${model}`,
      codexEnv: `CODEX_BASE_URL=${localEndpoint}
CODEX_API_KEY=${key}
CODEX_MODEL=${model}`,
      cursorEnv: `OPENAI_BASE_URL=${localEndpoint}
OPENAI_API_KEY=${key}
OPENAI_MODEL=${model}`,
      claudeCodeEnv: `ANTHROPIC_BASE_URL=${localEndpoint}
ANTHROPIC_API_KEY=${key}
ANTHROPIC_MODEL=${model}`,
    };
  }, [result?.routerKey, sampleModel]);

  const presetSnippet = useMemo(() => {
    switch (preset) {
      case "claude":
        return snippets.claudeCodeEnv;
      case "cursor":
        return snippets.cursorEnv;
      case "codex":
        return snippets.codexEnv;
      case "curl":
        return snippets.curl;
      case "openai":
      default:
        return snippets.openaiEnv;
    }
  }, [preset, snippets]);

  const envBundle = useMemo(() => {
    const key = result?.routerKey || "<router-api-key>";
    const model = sampleModel || "claude-sonnet-5";
    return `# StaliRouter quick environment
# Generated by Stali Quick Setup
STALIROUTER_BASE_URL=${localEndpoint}
STALIROUTER_API_KEY=${key}
STALIROUTER_MODEL=${model}

# OpenAI-compatible tools
OPENAI_BASE_URL=${localEndpoint}
OPENAI_API_KEY=${key}
OPENAI_MODEL=${model}

# Claude-compatible tools
ANTHROPIC_BASE_URL=${localEndpoint}
ANTHROPIC_API_KEY=${key}
ANTHROPIC_MODEL=${model}

# Codex
CODEX_BASE_URL=${localEndpoint}
CODEX_API_KEY=${key}
CODEX_MODEL=${model}
`;
  }, [localEndpoint, result?.routerKey, sampleModel]);

  const downloadEnvFile = () => {
    const blob = new Blob([envBundle], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".env.stalirouter";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  useEffect(() => {
    const loadProfile = async () => {
      setProfileLoading(true);
      try {
        const res = await fetch("/api/stali/profile", { cache: "no-store" });
        const data = await res.json();
        if (res.ok) {
          if (data?.activeBaseUrl) setBaseUrl(data.activeBaseUrl);
          if (Array.isArray(data?.recommendedModels) && data.recommendedModels.length > 0) {
            setModelsInput(data.recommendedModels.join(", "));
          }
          if (data?.routerApiKey || data?.enabledModels?.length) {
            setResult((prev) => prev || {
              ok: true,
              message: "Loaded current Stali profile.",
              models: data.enabledModels || data.recommendedModels || [],
              routerKey: data.routerApiKey || null,
            });
          }
        }
      } catch {
        // Ignore profile bootstrap failures; user can still run manual setup.
      } finally {
        setProfileLoading(false);
      }
    };
    loadProfile();
  }, []);

  const runSetup = async () => {
    setLoading(true);
    setResult(null);
    try {
      const normalizedBase = normalizeBase(baseUrl);
      if (!normalizedBase || !apiKey.trim()) {
        setResult({ ok: false, message: "Base URL and API key are required." });
        return;
      }

      const res = await fetch("/api/stali/setup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          baseUrl: normalizedBase,
          apiKey: apiKey.trim(),
          models: selectedModels,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data?.error || "Setup failed");
      }

      setResult({
        ok: true,
        message: data.message || "Stali setup completed successfully.",
        models: data.models || data.enabledModels || [],
        routerKey: data.routerKey || data.routerApiKey || null,
      });
    } catch (err) {
      setResult({ ok: false, message: err?.message || "Setup failed" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      <Card>
        <div className="flex flex-col gap-5">
          <div>
            <h1 className="text-2xl font-semibold">Stali Quick Setup</h1>
            <p className="text-sm text-text-muted mt-1">
              One flow only: base URL + Stali API key + models. Internal routing remains hidden.
            </p>
            {profileLoading ? (
              <p className="text-xs text-text-muted mt-2">Loading current Stali profile...</p>
            ) : null}
          </div>

          <Input
            label="Stali Base URL"
            value={baseUrl}
            onChange={(e) => setBaseUrl(e.target.value)}
            placeholder="https://api.stali.vn/v1"
          />
          <Input
            label="Stali API Key"
            type="password"
            value={apiKey}
            onChange={(e) => setApiKey(e.target.value)}
            placeholder="sk-..."
          />
          <Input
            label="Models (comma separated)"
            value={modelsInput}
            onChange={(e) => setModelsInput(e.target.value)}
            placeholder={DEFAULT_MODELS.join(", ")}
            hint="Only models available on your key will be enabled."
          />

          <div className="flex flex-wrap gap-2">
            {selectedModels.map((m) => (
              <Badge key={m} variant="default" size="sm">{m}</Badge>
            ))}
          </div>

          <Button onClick={runSetup} loading={loading} disabled={!apiKey.trim()}>
            Apply Stali Setup
          </Button>

          {result && (
            <div className={`rounded-lg border p-3 text-sm ${result.ok ? "border-green-500/30 bg-green-500/10" : "border-red-500/30 bg-red-500/10"}`}>
              <p className="font-medium">{result.message}</p>
              {result.ok && (
                <>
                  <p className="mt-1">Enabled models: {(result.models || []).join(", ")}</p>
                  {result.routerKey ? <p className="mt-1">Router key: <code>{result.routerKey}</code></p> : null}
                </>
              )}
            </div>
          )}

          {result?.ok && (
            <div className="rounded-lg border p-4 bg-bg-subtle">
              <h2 className="text-base font-semibold mb-3">Quick Copy for Client Apps</h2>
              <p className="text-xs text-text-muted mb-3">
                Use these snippets directly with local StaliRouter endpoint.
              </p>

              <div className="mb-3 flex flex-wrap gap-2">
                {[
                  { id: "claude", label: "Claude Code" },
                  { id: "cursor", label: "Cursor" },
                  { id: "codex", label: "Codex" },
                  { id: "openai", label: "OpenAI SDK" },
                  { id: "curl", label: "cURL Test" },
                ].map((opt) => (
                  <button
                    key={opt.id}
                    type="button"
                    onClick={() => setPreset(opt.id)}
                    className={`px-2.5 py-1.5 rounded-lg text-xs border transition-colors ${
                      preset === opt.id
                        ? "border-primary bg-primary/10 text-primary"
                        : "border-border text-text-muted hover:text-text-main hover:border-primary/50"
                    }`}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>

              <div className="space-y-3">
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm font-medium">Preset snippet</span>
                    <Button size="sm" variant="secondary" onClick={() => copy(presetSnippet)}>
                      {copied ? "Copied" : "Copy"}
                    </Button>
                  </div>
                  <pre className="text-xs p-2 rounded bg-black/5 dark:bg-white/5 overflow-x-auto">{presetSnippet}</pre>
                </div>
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm font-medium">Export .env.stalirouter</span>
                    <div className="flex items-center gap-2">
                      <Button size="sm" variant="secondary" onClick={() => copy(envBundle)}>
                        {copied ? "Copied" : "Copy"}
                      </Button>
                      <Button size="sm" onClick={downloadEnvFile}>
                        Download
                      </Button>
                    </div>
                  </div>
                  <pre className="text-xs p-2 rounded bg-black/5 dark:bg-white/5 overflow-x-auto">{envBundle}</pre>
                </div>
              </div>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}

